/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormReadXml.java
 *
 * Created on Apr 26, 2012, 11:12:15 AM
 */
package thesis.fileforms;

import java.awt.Color;
import java.awt.Dimension;
import java.io.Closeable;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author BSTNC
 */
public final class FormReadXml extends javax.swing.JInternalFrame {

    /** Creates new form FormReadXml */
    public FormReadXml() {
        initComponents();
        if (thesis.FormAna.XmlURL != null) {
            lblUyari.setText(thesis.FormAna.XmlURL + " file loaded !");
        } else {
            lblUyari.setText("Please load a xml file !");
            lblUyari.setForeground(Color.red);
        }
        java.io.File currentDir = new java.io.File("");
        //txtFolderURL.setText(currentDir.getAbsolutePath() + "/xmlDenemeleri");
        txtFolderURL.setText("C:\\ThesisApp\\YeniYapi\\xmlDenemeleri");
        ReadDirectory(txtFolderURL.getText());
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtXmlContents = new javax.swing.JTextArea();
        btnLoadSystem = new javax.swing.JButton();
        lblUyari = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstXmlFiles = new javax.swing.JList();
        btnRefreshContent = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnChooseFolder = new javax.swing.JButton();
        txtFolderURL = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSaveManuel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblSelectedFileURL = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Read Xml File");
        setPreferredSize(new java.awt.Dimension(1300, 600));
        setVisible(true);

        txtXmlContents.setColumns(20);
        txtXmlContents.setRows(5);
        jScrollPane1.setViewportView(txtXmlContents);

        btnLoadSystem.setText("Load to System");
        btnLoadSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadSystemActionPerformed(evt);
            }
        });

        lblUyari.setText("!..");

        jLabel2.setText("Folder Content :");

        lstXmlFiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstXmlFilesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstXmlFiles);

        btnRefreshContent.setText("Refresh Folder Content");
        btnRefreshContent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshContentActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnChooseFolder.setText("Choose Folder");
        btnChooseFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseFolderActionPerformed(evt);
            }
        });

        jLabel3.setText("Folder URL :");

        jLabel1.setText("Selected Xml File Content :");

        btnSaveManuel.setText("Save Manuel Changes");
        btnSaveManuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveManuelActionPerformed(evt);
            }
        });

        jLabel4.setText("Selected Xml File URL       :");

        lblSelectedFileURL.setText("!!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblUyari))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFolderURL, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnChooseFolder))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(btnRefreshContent, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSelectedFileURL))
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLoadSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btnSaveManuel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblUyari)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFolderURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(btnChooseFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnRefreshContent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblSelectedFileURL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSaveManuel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLoadSystem, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DefaultListModel model = new DefaultListModel();
private void btnLoadSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadSystemActionPerformed
// TODO add your handling code here:
    if (!txtXmlContents.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Seçilen Xml Dosyası Sisteme Yüklendi. Edit'leme işlemleri için hazır !");
    }

        thesis.FormAna.XmlURL = txtFolderURL.getText() + "\\" + lstXmlFiles.getSelectedValue().toString();
}//GEN-LAST:event_btnLoadSystemActionPerformed

private void btnRefreshContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshContentActionPerformed
// TODO add your handling code here:

    ReadDirectory(txtFolderURL.getText());
}//GEN-LAST:event_btnRefreshContentActionPerformed

private void btnChooseFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseFolderActionPerformed
// TODO add your handling code here:
    JFileChooser chooser;
    chooser = new JFileChooser();
    chooser.setCurrentDirectory(new java.io.File("."));
    chooser.setDialogTitle("Select a folder...");
    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    //
    // disable the "All files" option.
    //
    chooser.setAcceptAllFileFilterUsed(false);
    //    
    if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
        txtFolderURL.setText(chooser.getSelectedFile().toString());
    }

    ReadDirectory(txtFolderURL.getText());
    lstXmlFiles.setModel(model);
}//GEN-LAST:event_btnChooseFolderActionPerformed

private void lstXmlFilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstXmlFilesMouseClicked
    try {
        // TODO add your handling code here:
        Fonksiyon sys = new Fonksiyon();

        txtXmlContents.setText(sys.readFileContent(txtFolderURL.getText() + "\\" + lstXmlFiles.getSelectedValue().toString()));
        lblSelectedFileURL.setText(txtFolderURL.getText() + "\\" + lstXmlFiles.getSelectedValue().toString());
    } catch (FileNotFoundException ex) {
        ex.printStackTrace();
    } catch (IOException ex) {
        ex.printStackTrace();
    }

}//GEN-LAST:event_lstXmlFilesMouseClicked

private void btnSaveManuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveManuelActionPerformed
        try {
            // TODO add your handling code here:
               
                String fileURL = txtFolderURL.getText() + "\\" + lstXmlFiles.getSelectedValue().toString();
                writeFile(fileURL,txtXmlContents.getText());
                JOptionPane.showMessageDialog(this, "Manuel Kayıt Başarıyla Gerçekleşti !");
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    
}//GEN-LAST:event_btnSaveManuelActionPerformed
public static void writeFile(String filename, String text) throws IOException {
    FileOutputStream fos = null;
    try {
        fos = new FileOutputStream(filename);
        fos.write(text.getBytes("ISO-8859-1"));
    } catch (IOException e) {
        close(fos);
        throw e;
    }
}
public static void close(Closeable closeable) {
    try {
        closeable.close();
    } catch(IOException ignored) {
    }
}
    public String ReadDirectory(String path) {
        //path = "C:";
        model.clear();
        String files="";
        File folder = new File(path);
        File[] listOfFiles = folder.listFiles();

        for (int i = 0; i < listOfFiles.length; i++) {
            if (listOfFiles[i].isFile()) {
                files = listOfFiles[i].getName();
                if (files.endsWith(".xml") || files.endsWith(".XML")) {
                    System.out.println(files);
                    model.addElement(files);
                }
            }
        }
        lstXmlFiles.setModel(model);
        
        return files;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseFolder;
    private javax.swing.JButton btnLoadSystem;
    private javax.swing.JButton btnRefreshContent;
    private javax.swing.JButton btnSaveManuel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblSelectedFileURL;
    private javax.swing.JLabel lblUyari;
    private javax.swing.JList lstXmlFiles;
    private javax.swing.JTextField txtFolderURL;
    private javax.swing.JTextArea txtXmlContents;
    // End of variables declaration//GEN-END:variables
}
