/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormDeleteTarget.java
 *
 * Created on Apr 26, 2012, 3:07:45 PM
 */
package thesis.targets;

import java.awt.Color;
import java.io.File;
import java.io.FileWriter;
import java.util.List;
import javax.swing.JOptionPane;
import org.jdom.*;
import org.jdom.input.SAXBuilder;
import org.jdom.output.XMLOutputter;

/**
 *
 * @author BSTNC
 */
public class FormDeleteTarget extends javax.swing.JInternalFrame {

    /** Creates new form FormDeleteTarget */
    public FormDeleteTarget() {
        initComponents();
        if (thesis.FormAna.XmlURL != null) {
            lblUyari.setText(thesis.FormAna.XmlURL + " file loaded !");
        } else {
            lblUyari.setText("Please load a xml file !");
            lblUyari.setForeground(Color.red);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUyari = new javax.swing.JLabel();
        txtTargetID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Delete Target");
        setVisible(true);

        lblUyari.setText("!..");

        jLabel1.setText("Target ID :");

        jButton1.setText("Delete Target");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtTargetID, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblUyari))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblUyari)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTargetID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:

    SAXBuilder builder = new SAXBuilder();
    File xmlFile = new File(thesis.FormAna.XmlURL);
    int bulundu =0;
    try {

        Document document = (Document) builder.build(xmlFile);
        Element rootNode = document.getRootElement();
        List TargetList_ = rootNode.getChildren("target");
        for (int i = 0; i < TargetList_.size(); i++) {
            Element node = (Element) TargetList_.get(i);
            if (node.getAttributeValue("id").equals(txtTargetID.getText())) {
                bulundu=1;
                int sonuc = JOptionPane.showConfirmDialog(null, node.getAttributeValue("name")+" target'ını silmek İstiyor musunuz ?", "Dikkat !", JOptionPane.YES_NO_CANCEL_OPTION);
                if (sonuc == 0) {
                    TargetList_.remove(node);
                    JOptionPane.showMessageDialog(this, "Target Başarıyla Silindi !");
                }

                break;
            }

            //System.out.println(node.getAttributeValue("id"));
        }
        if (bulundu==0) {
            JOptionPane.showMessageDialog(this, "Target Bulunamadı !");
        }
        document.setRootElement(rootNode);
        XMLOutputter xmlOutputter = new XMLOutputter();
        xmlOutputter.output(document, new FileWriter(thesis.FormAna.XmlURL));

    } catch (Exception a) {
        //JOptionPane.showMessageDialog(this, "Target Bulunamadı !");
    }
}//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblUyari;
    private javax.swing.JTextField txtTargetID;
    // End of variables declaration//GEN-END:variables
}
