/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RunInterface.java
 *
 * Created on May 5, 2012, 12:54:58 AM
 */
package thesis;

import thesis.fileforms.Fonksiyon;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.*;
import java.util.List;
import org.jdom.*;
import org.jdom.input.SAXBuilder;

/**
 *
 * @author BSTNC
 */
public class RunInterface extends javax.swing.JInternalFrame {

    /** Creates new form RunInterface */
    public RunInterface() {
        initComponents();
        
        try {

            GetxmlContent();
            getTargets();

        } catch (JDOMException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    public void getTargets() throws JDOMException, IOException {

        // model olusturup JListe ekleme yapiyoruz
        SAXBuilder builder = new SAXBuilder();
        File xmlFile = new File(thesis.FormAna.XmlURL);

        Document document = (Document) builder.build(xmlFile);
        Element rootNode = document.getRootElement();
        List tl = rootNode.getChildren("target");
        Object data[] = new Object[4];

        for (int i = 0; i < tl.size(); i++) {
            Element node = (Element) tl.get(i);

            data[0] = node.getAttributeValue("id").toString();
            data[1] = node.getAttributeValue("name").toString();

            System.out.println(data[1]);
            cmbTargets.addItem(data[1]);

        }

    }

    private void GetxmlContent() {
        try {
            Fonksiyon sys = new Fonksiyon();
            txtXmlContent.setText(sys.readFileContent(thesis.FormAna.XmlURL));
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtXmlContent = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRunResults = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cmbAntOptionalParameter = new javax.swing.JComboBox();
        txtAntOptionalParameterValue = new javax.swing.JTextField();
        cmbTargets = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btnRun = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Run Interface");
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtXmlContent.setColumns(20);
        txtXmlContent.setRows(5);
        jScrollPane1.setViewportView(txtXmlContent);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 750, 210));

        txtRunResults.setColumns(20);
        txtRunResults.setRows(5);
        jScrollPane2.setViewportView(txtRunResults);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 755, 171));

        jLabel2.setText("Run Results :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Set Ant Parameters"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbAntOptionalParameter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "none", "-help -h              ", "-projecthelp -p       ", "-version               ", "-diagnostics                               ", "-quiet -q             ", "-verbose -v           ", "-debug -d             ", "-emacs -e             ", "-lib <path>            ", "-logfile <file>        ", "  -l     <file>        ", "-logger <classname>    ", "-listener <classname>  ", "-noinput               ", "-buildfile <file>      ", "  -file    <file>      ", "  -f       <file>      ", "-D <property>=<value>   ", "-keep-going -k                             ", "-propertyfile <name>                        ", "-inputhandler <class>  ", "-find <file>           ", "  -s  <file>           ", "-nice  number                                 ", "-nouserlib                                  ", "-noclasspath           ", "-autoproxy             ", "-main <class> " }));
        jPanel1.add(cmbAntOptionalParameter, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 53, 210, 31));
        jPanel1.add(txtAntOptionalParameterValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 107, 210, 30));

        cmbTargets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTargetsActionPerformed(evt);
            }
        });
        jPanel1.add(cmbTargets, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 200, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 27, 10, 110));

        jLabel3.setText("Optional Parameter :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        btnRun.setText("RUN Target");
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });
        jPanel1.add(btnRun, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 120, 34));

        jLabel4.setText("Value :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 760, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batOlustur(String BuildFilePath, String CalisTarget) {
        try {
            String batIcerik="";
            java.io.File currentDir = new java.io.File("");
            if (cmbAntOptionalParameter.getSelectedIndex()==0) {
                batIcerik="ant -file "+BuildFilePath+" "+CalisTarget;
            }else{
                String [] a = cmbAntOptionalParameter.getSelectedItem().toString().split(" ");
                batIcerik="ant -file "+BuildFilePath+" "+a[0]+" "+txtAntOptionalParameterValue.getText().toString()+" "+CalisTarget;
            }
             
            writeFile(currentDir.getAbsolutePath()+"\\ant-1.bat", batIcerik);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    public static void writeFile(String filename, String text) throws IOException {
        FileOutputStream fos = null;
        try {
            fos = new FileOutputStream(filename);
            fos.write(text.getBytes("UTF-8"));
            close(fos);
        } catch (IOException e) {
            close(fos);
            throw e;
        }
    }

    public static void close(Closeable closeable) {
        try {
            closeable.close();
        } catch (IOException ignored) {
        }
    }
private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
// TODO add your handling code here:
    //BAT DOSYASI OLUSTUR
    batOlustur(thesis.FormAna.XmlURL,cmbTargets.getSelectedItem().toString());
    //SET ANT OPTIONAL PARAMETER
    txtRunResults.setText("basladik");
    try {
        String line;
        java.io.File currentDir = new java.io.File("");
        //Process p = Runtime.getRuntime().exec("ant -file c:/Ant/build.xml compile");
        Process p = Runtime.getRuntime().exec(currentDir.getAbsolutePath()+"\\ant-1.bat");

        BufferedReader bri = new BufferedReader(new InputStreamReader(p.getInputStream()));
//        BufferedReader bre = new BufferedReader(new InputStreamReader(p.getErrorStream()));
        while ((line = bri.readLine()) != null) {
            txtRunResults.setText(txtRunResults.getText() + "\n" + line);
            System.out.println(line);
        }
        bri.close();
//        while ((line = bre.readLine()) != null) {
//            System.out.println(line);
//            txtRunResults.setText(txtRunResults.getText() + "\n" + line);
//        }
//        bre.close();
//        p.waitFor();
        System.out.println("Done.");
        txtRunResults.setText(txtRunResults.getText() + "\n" + "Done");
    } catch (Exception err) {
        txtRunResults.setText(txtRunResults.getText() + "\n" + err.toString());
        //err.printStackTrace();
    }
}//GEN-LAST:event_btnRunActionPerformed

private void cmbTargetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTargetsActionPerformed
// TODO add your handling code here:
    
}//GEN-LAST:event_cmbTargetsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRun;
    private javax.swing.JComboBox cmbAntOptionalParameter;
    private javax.swing.JComboBox cmbTargets;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtAntOptionalParameterValue;
    private javax.swing.JTextArea txtRunResults;
    private javax.swing.JTextArea txtXmlContent;
    // End of variables declaration//GEN-END:variables
}
